// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// source: Social/AsyncAPI/statistic.yaml (0.1.0)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: accelbyte-asyncapi/social/statistic/v1/statistic.proto

package statistic

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StatManagementStatCreatedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatManagementStatCreatedService/OnMessage"
)

// StatManagementStatCreatedServiceClient is the client API for StatManagementStatCreatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatManagementStatCreatedServiceClient interface {
	OnMessage(ctx context.Context, in *StatCreated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statManagementStatCreatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatManagementStatCreatedServiceClient(cc grpc.ClientConnInterface) StatManagementStatCreatedServiceClient {
	return &statManagementStatCreatedServiceClient{cc}
}

func (c *statManagementStatCreatedServiceClient) OnMessage(ctx context.Context, in *StatCreated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatManagementStatCreatedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatManagementStatCreatedServiceServer is the server API for StatManagementStatCreatedService service.
// All implementations must embed UnimplementedStatManagementStatCreatedServiceServer
// for forward compatibility
type StatManagementStatCreatedServiceServer interface {
	OnMessage(context.Context, *StatCreated) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatManagementStatCreatedServiceServer()
}

// UnimplementedStatManagementStatCreatedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatManagementStatCreatedServiceServer struct {
}

func (UnimplementedStatManagementStatCreatedServiceServer) OnMessage(context.Context, *StatCreated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatManagementStatCreatedServiceServer) mustEmbedUnimplementedStatManagementStatCreatedServiceServer() {
}

// UnsafeStatManagementStatCreatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatManagementStatCreatedServiceServer will
// result in compilation errors.
type UnsafeStatManagementStatCreatedServiceServer interface {
	mustEmbedUnimplementedStatManagementStatCreatedServiceServer()
}

func RegisterStatManagementStatCreatedServiceServer(s grpc.ServiceRegistrar, srv StatManagementStatCreatedServiceServer) {
	s.RegisterService(&StatManagementStatCreatedService_ServiceDesc, srv)
}

func _StatManagementStatCreatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatCreated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatManagementStatCreatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatManagementStatCreatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatManagementStatCreatedServiceServer).OnMessage(ctx, req.(*StatCreated))
	}
	return interceptor(ctx, in, info, handler)
}

// StatManagementStatCreatedService_ServiceDesc is the grpc.ServiceDesc for StatManagementStatCreatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatManagementStatCreatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatManagementStatCreatedService",
	HandlerType: (*StatManagementStatCreatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatManagementStatCreatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatManagementStatDeletedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatManagementStatDeletedService/OnMessage"
)

// StatManagementStatDeletedServiceClient is the client API for StatManagementStatDeletedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatManagementStatDeletedServiceClient interface {
	OnMessage(ctx context.Context, in *StatDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statManagementStatDeletedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatManagementStatDeletedServiceClient(cc grpc.ClientConnInterface) StatManagementStatDeletedServiceClient {
	return &statManagementStatDeletedServiceClient{cc}
}

func (c *statManagementStatDeletedServiceClient) OnMessage(ctx context.Context, in *StatDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatManagementStatDeletedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatManagementStatDeletedServiceServer is the server API for StatManagementStatDeletedService service.
// All implementations must embed UnimplementedStatManagementStatDeletedServiceServer
// for forward compatibility
type StatManagementStatDeletedServiceServer interface {
	OnMessage(context.Context, *StatDeleted) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatManagementStatDeletedServiceServer()
}

// UnimplementedStatManagementStatDeletedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatManagementStatDeletedServiceServer struct {
}

func (UnimplementedStatManagementStatDeletedServiceServer) OnMessage(context.Context, *StatDeleted) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatManagementStatDeletedServiceServer) mustEmbedUnimplementedStatManagementStatDeletedServiceServer() {
}

// UnsafeStatManagementStatDeletedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatManagementStatDeletedServiceServer will
// result in compilation errors.
type UnsafeStatManagementStatDeletedServiceServer interface {
	mustEmbedUnimplementedStatManagementStatDeletedServiceServer()
}

func RegisterStatManagementStatDeletedServiceServer(s grpc.ServiceRegistrar, srv StatManagementStatDeletedServiceServer) {
	s.RegisterService(&StatManagementStatDeletedService_ServiceDesc, srv)
}

func _StatManagementStatDeletedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatDeleted)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatManagementStatDeletedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatManagementStatDeletedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatManagementStatDeletedServiceServer).OnMessage(ctx, req.(*StatDeleted))
	}
	return interceptor(ctx, in, info, handler)
}

// StatManagementStatDeletedService_ServiceDesc is the grpc.ServiceDesc for StatManagementStatDeletedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatManagementStatDeletedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatManagementStatDeletedService",
	HandlerType: (*StatManagementStatDeletedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatManagementStatDeletedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatManagementStatUpdatedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatManagementStatUpdatedService/OnMessage"
)

// StatManagementStatUpdatedServiceClient is the client API for StatManagementStatUpdatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatManagementStatUpdatedServiceClient interface {
	OnMessage(ctx context.Context, in *StatUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statManagementStatUpdatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatManagementStatUpdatedServiceClient(cc grpc.ClientConnInterface) StatManagementStatUpdatedServiceClient {
	return &statManagementStatUpdatedServiceClient{cc}
}

func (c *statManagementStatUpdatedServiceClient) OnMessage(ctx context.Context, in *StatUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatManagementStatUpdatedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatManagementStatUpdatedServiceServer is the server API for StatManagementStatUpdatedService service.
// All implementations must embed UnimplementedStatManagementStatUpdatedServiceServer
// for forward compatibility
type StatManagementStatUpdatedServiceServer interface {
	OnMessage(context.Context, *StatUpdated) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatManagementStatUpdatedServiceServer()
}

// UnimplementedStatManagementStatUpdatedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatManagementStatUpdatedServiceServer struct {
}

func (UnimplementedStatManagementStatUpdatedServiceServer) OnMessage(context.Context, *StatUpdated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatManagementStatUpdatedServiceServer) mustEmbedUnimplementedStatManagementStatUpdatedServiceServer() {
}

// UnsafeStatManagementStatUpdatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatManagementStatUpdatedServiceServer will
// result in compilation errors.
type UnsafeStatManagementStatUpdatedServiceServer interface {
	mustEmbedUnimplementedStatManagementStatUpdatedServiceServer()
}

func RegisterStatManagementStatUpdatedServiceServer(s grpc.ServiceRegistrar, srv StatManagementStatUpdatedServiceServer) {
	s.RegisterService(&StatManagementStatUpdatedService_ServiceDesc, srv)
}

func _StatManagementStatUpdatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatUpdated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatManagementStatUpdatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatManagementStatUpdatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatManagementStatUpdatedServiceServer).OnMessage(ctx, req.(*StatUpdated))
	}
	return interceptor(ctx, in, info, handler)
}

// StatManagementStatUpdatedService_ServiceDesc is the grpc.ServiceDesc for StatManagementStatUpdatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatManagementStatUpdatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatManagementStatUpdatedService",
	HandlerType: (*StatManagementStatUpdatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatManagementStatUpdatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatManagementStatImportedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatManagementStatImportedService/OnMessage"
)

// StatManagementStatImportedServiceClient is the client API for StatManagementStatImportedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatManagementStatImportedServiceClient interface {
	OnMessage(ctx context.Context, in *StatImported, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statManagementStatImportedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatManagementStatImportedServiceClient(cc grpc.ClientConnInterface) StatManagementStatImportedServiceClient {
	return &statManagementStatImportedServiceClient{cc}
}

func (c *statManagementStatImportedServiceClient) OnMessage(ctx context.Context, in *StatImported, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatManagementStatImportedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatManagementStatImportedServiceServer is the server API for StatManagementStatImportedService service.
// All implementations must embed UnimplementedStatManagementStatImportedServiceServer
// for forward compatibility
type StatManagementStatImportedServiceServer interface {
	OnMessage(context.Context, *StatImported) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatManagementStatImportedServiceServer()
}

// UnimplementedStatManagementStatImportedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatManagementStatImportedServiceServer struct {
}

func (UnimplementedStatManagementStatImportedServiceServer) OnMessage(context.Context, *StatImported) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatManagementStatImportedServiceServer) mustEmbedUnimplementedStatManagementStatImportedServiceServer() {
}

// UnsafeStatManagementStatImportedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatManagementStatImportedServiceServer will
// result in compilation errors.
type UnsafeStatManagementStatImportedServiceServer interface {
	mustEmbedUnimplementedStatManagementStatImportedServiceServer()
}

func RegisterStatManagementStatImportedServiceServer(s grpc.ServiceRegistrar, srv StatManagementStatImportedServiceServer) {
	s.RegisterService(&StatManagementStatImportedService_ServiceDesc, srv)
}

func _StatManagementStatImportedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatImported)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatManagementStatImportedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatManagementStatImportedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatManagementStatImportedServiceServer).OnMessage(ctx, req.(*StatImported))
	}
	return interceptor(ctx, in, info, handler)
}

// StatManagementStatImportedService_ServiceDesc is the grpc.ServiceDesc for StatManagementStatImportedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatManagementStatImportedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatManagementStatImportedService",
	HandlerType: (*StatManagementStatImportedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatManagementStatImportedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatManagementStatExportedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatManagementStatExportedService/OnMessage"
)

// StatManagementStatExportedServiceClient is the client API for StatManagementStatExportedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatManagementStatExportedServiceClient interface {
	OnMessage(ctx context.Context, in *StatExported, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statManagementStatExportedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatManagementStatExportedServiceClient(cc grpc.ClientConnInterface) StatManagementStatExportedServiceClient {
	return &statManagementStatExportedServiceClient{cc}
}

func (c *statManagementStatExportedServiceClient) OnMessage(ctx context.Context, in *StatExported, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatManagementStatExportedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatManagementStatExportedServiceServer is the server API for StatManagementStatExportedService service.
// All implementations must embed UnimplementedStatManagementStatExportedServiceServer
// for forward compatibility
type StatManagementStatExportedServiceServer interface {
	OnMessage(context.Context, *StatExported) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatManagementStatExportedServiceServer()
}

// UnimplementedStatManagementStatExportedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatManagementStatExportedServiceServer struct {
}

func (UnimplementedStatManagementStatExportedServiceServer) OnMessage(context.Context, *StatExported) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatManagementStatExportedServiceServer) mustEmbedUnimplementedStatManagementStatExportedServiceServer() {
}

// UnsafeStatManagementStatExportedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatManagementStatExportedServiceServer will
// result in compilation errors.
type UnsafeStatManagementStatExportedServiceServer interface {
	mustEmbedUnimplementedStatManagementStatExportedServiceServer()
}

func RegisterStatManagementStatExportedServiceServer(s grpc.ServiceRegistrar, srv StatManagementStatExportedServiceServer) {
	s.RegisterService(&StatManagementStatExportedService_ServiceDesc, srv)
}

func _StatManagementStatExportedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatExported)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatManagementStatExportedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatManagementStatExportedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatManagementStatExportedServiceServer).OnMessage(ctx, req.(*StatExported))
	}
	return interceptor(ctx, in, info, handler)
}

// StatManagementStatExportedService_ServiceDesc is the grpc.ServiceDesc for StatManagementStatExportedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatManagementStatExportedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatManagementStatExportedService",
	HandlerType: (*StatManagementStatExportedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatManagementStatExportedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatisticStatItemCreatedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatisticStatItemCreatedService/OnMessage"
)

// StatisticStatItemCreatedServiceClient is the client API for StatisticStatItemCreatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticStatItemCreatedServiceClient interface {
	OnMessage(ctx context.Context, in *StatItemCreated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statisticStatItemCreatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticStatItemCreatedServiceClient(cc grpc.ClientConnInterface) StatisticStatItemCreatedServiceClient {
	return &statisticStatItemCreatedServiceClient{cc}
}

func (c *statisticStatItemCreatedServiceClient) OnMessage(ctx context.Context, in *StatItemCreated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatisticStatItemCreatedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticStatItemCreatedServiceServer is the server API for StatisticStatItemCreatedService service.
// All implementations must embed UnimplementedStatisticStatItemCreatedServiceServer
// for forward compatibility
type StatisticStatItemCreatedServiceServer interface {
	OnMessage(context.Context, *StatItemCreated) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatisticStatItemCreatedServiceServer()
}

// UnimplementedStatisticStatItemCreatedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticStatItemCreatedServiceServer struct {
}

func (UnimplementedStatisticStatItemCreatedServiceServer) OnMessage(context.Context, *StatItemCreated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatisticStatItemCreatedServiceServer) mustEmbedUnimplementedStatisticStatItemCreatedServiceServer() {
}

// UnsafeStatisticStatItemCreatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticStatItemCreatedServiceServer will
// result in compilation errors.
type UnsafeStatisticStatItemCreatedServiceServer interface {
	mustEmbedUnimplementedStatisticStatItemCreatedServiceServer()
}

func RegisterStatisticStatItemCreatedServiceServer(s grpc.ServiceRegistrar, srv StatisticStatItemCreatedServiceServer) {
	s.RegisterService(&StatisticStatItemCreatedService_ServiceDesc, srv)
}

func _StatisticStatItemCreatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatItemCreated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticStatItemCreatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticStatItemCreatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticStatItemCreatedServiceServer).OnMessage(ctx, req.(*StatItemCreated))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticStatItemCreatedService_ServiceDesc is the grpc.ServiceDesc for StatisticStatItemCreatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticStatItemCreatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatisticStatItemCreatedService",
	HandlerType: (*StatisticStatItemCreatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatisticStatItemCreatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatisticStatItemUpdatedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatisticStatItemUpdatedService/OnMessage"
)

// StatisticStatItemUpdatedServiceClient is the client API for StatisticStatItemUpdatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticStatItemUpdatedServiceClient interface {
	OnMessage(ctx context.Context, in *StatItemUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statisticStatItemUpdatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticStatItemUpdatedServiceClient(cc grpc.ClientConnInterface) StatisticStatItemUpdatedServiceClient {
	return &statisticStatItemUpdatedServiceClient{cc}
}

func (c *statisticStatItemUpdatedServiceClient) OnMessage(ctx context.Context, in *StatItemUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatisticStatItemUpdatedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticStatItemUpdatedServiceServer is the server API for StatisticStatItemUpdatedService service.
// All implementations must embed UnimplementedStatisticStatItemUpdatedServiceServer
// for forward compatibility
type StatisticStatItemUpdatedServiceServer interface {
	OnMessage(context.Context, *StatItemUpdated) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatisticStatItemUpdatedServiceServer()
}

// UnimplementedStatisticStatItemUpdatedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticStatItemUpdatedServiceServer struct {
}

func (UnimplementedStatisticStatItemUpdatedServiceServer) OnMessage(context.Context, *StatItemUpdated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatisticStatItemUpdatedServiceServer) mustEmbedUnimplementedStatisticStatItemUpdatedServiceServer() {
}

// UnsafeStatisticStatItemUpdatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticStatItemUpdatedServiceServer will
// result in compilation errors.
type UnsafeStatisticStatItemUpdatedServiceServer interface {
	mustEmbedUnimplementedStatisticStatItemUpdatedServiceServer()
}

func RegisterStatisticStatItemUpdatedServiceServer(s grpc.ServiceRegistrar, srv StatisticStatItemUpdatedServiceServer) {
	s.RegisterService(&StatisticStatItemUpdatedService_ServiceDesc, srv)
}

func _StatisticStatItemUpdatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatItemUpdated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticStatItemUpdatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticStatItemUpdatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticStatItemUpdatedServiceServer).OnMessage(ctx, req.(*StatItemUpdated))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticStatItemUpdatedService_ServiceDesc is the grpc.ServiceDesc for StatisticStatItemUpdatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticStatItemUpdatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatisticStatItemUpdatedService",
	HandlerType: (*StatisticStatItemUpdatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatisticStatItemUpdatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatisticStatItemDeletedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatisticStatItemDeletedService/OnMessage"
)

// StatisticStatItemDeletedServiceClient is the client API for StatisticStatItemDeletedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticStatItemDeletedServiceClient interface {
	OnMessage(ctx context.Context, in *StatItemDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statisticStatItemDeletedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticStatItemDeletedServiceClient(cc grpc.ClientConnInterface) StatisticStatItemDeletedServiceClient {
	return &statisticStatItemDeletedServiceClient{cc}
}

func (c *statisticStatItemDeletedServiceClient) OnMessage(ctx context.Context, in *StatItemDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatisticStatItemDeletedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticStatItemDeletedServiceServer is the server API for StatisticStatItemDeletedService service.
// All implementations must embed UnimplementedStatisticStatItemDeletedServiceServer
// for forward compatibility
type StatisticStatItemDeletedServiceServer interface {
	OnMessage(context.Context, *StatItemDeleted) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatisticStatItemDeletedServiceServer()
}

// UnimplementedStatisticStatItemDeletedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticStatItemDeletedServiceServer struct {
}

func (UnimplementedStatisticStatItemDeletedServiceServer) OnMessage(context.Context, *StatItemDeleted) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatisticStatItemDeletedServiceServer) mustEmbedUnimplementedStatisticStatItemDeletedServiceServer() {
}

// UnsafeStatisticStatItemDeletedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticStatItemDeletedServiceServer will
// result in compilation errors.
type UnsafeStatisticStatItemDeletedServiceServer interface {
	mustEmbedUnimplementedStatisticStatItemDeletedServiceServer()
}

func RegisterStatisticStatItemDeletedServiceServer(s grpc.ServiceRegistrar, srv StatisticStatItemDeletedServiceServer) {
	s.RegisterService(&StatisticStatItemDeletedService_ServiceDesc, srv)
}

func _StatisticStatItemDeletedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatItemDeleted)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticStatItemDeletedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticStatItemDeletedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticStatItemDeletedServiceServer).OnMessage(ctx, req.(*StatItemDeleted))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticStatItemDeletedService_ServiceDesc is the grpc.ServiceDesc for StatisticStatItemDeletedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticStatItemDeletedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatisticStatItemDeletedService",
	HandlerType: (*StatisticStatItemDeletedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatisticStatItemDeletedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatisticGlobalStatItemUpdatedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatisticGlobalStatItemUpdatedService/OnMessage"
)

// StatisticGlobalStatItemUpdatedServiceClient is the client API for StatisticGlobalStatItemUpdatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticGlobalStatItemUpdatedServiceClient interface {
	OnMessage(ctx context.Context, in *GlobalStatItemUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statisticGlobalStatItemUpdatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticGlobalStatItemUpdatedServiceClient(cc grpc.ClientConnInterface) StatisticGlobalStatItemUpdatedServiceClient {
	return &statisticGlobalStatItemUpdatedServiceClient{cc}
}

func (c *statisticGlobalStatItemUpdatedServiceClient) OnMessage(ctx context.Context, in *GlobalStatItemUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatisticGlobalStatItemUpdatedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticGlobalStatItemUpdatedServiceServer is the server API for StatisticGlobalStatItemUpdatedService service.
// All implementations must embed UnimplementedStatisticGlobalStatItemUpdatedServiceServer
// for forward compatibility
type StatisticGlobalStatItemUpdatedServiceServer interface {
	OnMessage(context.Context, *GlobalStatItemUpdated) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatisticGlobalStatItemUpdatedServiceServer()
}

// UnimplementedStatisticGlobalStatItemUpdatedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticGlobalStatItemUpdatedServiceServer struct {
}

func (UnimplementedStatisticGlobalStatItemUpdatedServiceServer) OnMessage(context.Context, *GlobalStatItemUpdated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatisticGlobalStatItemUpdatedServiceServer) mustEmbedUnimplementedStatisticGlobalStatItemUpdatedServiceServer() {
}

// UnsafeStatisticGlobalStatItemUpdatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticGlobalStatItemUpdatedServiceServer will
// result in compilation errors.
type UnsafeStatisticGlobalStatItemUpdatedServiceServer interface {
	mustEmbedUnimplementedStatisticGlobalStatItemUpdatedServiceServer()
}

func RegisterStatisticGlobalStatItemUpdatedServiceServer(s grpc.ServiceRegistrar, srv StatisticGlobalStatItemUpdatedServiceServer) {
	s.RegisterService(&StatisticGlobalStatItemUpdatedService_ServiceDesc, srv)
}

func _StatisticGlobalStatItemUpdatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalStatItemUpdated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticGlobalStatItemUpdatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticGlobalStatItemUpdatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticGlobalStatItemUpdatedServiceServer).OnMessage(ctx, req.(*GlobalStatItemUpdated))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticGlobalStatItemUpdatedService_ServiceDesc is the grpc.ServiceDesc for StatisticGlobalStatItemUpdatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticGlobalStatItemUpdatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatisticGlobalStatItemUpdatedService",
	HandlerType: (*StatisticGlobalStatItemUpdatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatisticGlobalStatItemUpdatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatCycleManagementStatCycleCreatedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatCycleManagementStatCycleCreatedService/OnMessage"
)

// StatCycleManagementStatCycleCreatedServiceClient is the client API for StatCycleManagementStatCycleCreatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatCycleManagementStatCycleCreatedServiceClient interface {
	OnMessage(ctx context.Context, in *StatCycleCreated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statCycleManagementStatCycleCreatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatCycleManagementStatCycleCreatedServiceClient(cc grpc.ClientConnInterface) StatCycleManagementStatCycleCreatedServiceClient {
	return &statCycleManagementStatCycleCreatedServiceClient{cc}
}

func (c *statCycleManagementStatCycleCreatedServiceClient) OnMessage(ctx context.Context, in *StatCycleCreated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatCycleManagementStatCycleCreatedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatCycleManagementStatCycleCreatedServiceServer is the server API for StatCycleManagementStatCycleCreatedService service.
// All implementations must embed UnimplementedStatCycleManagementStatCycleCreatedServiceServer
// for forward compatibility
type StatCycleManagementStatCycleCreatedServiceServer interface {
	OnMessage(context.Context, *StatCycleCreated) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatCycleManagementStatCycleCreatedServiceServer()
}

// UnimplementedStatCycleManagementStatCycleCreatedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatCycleManagementStatCycleCreatedServiceServer struct {
}

func (UnimplementedStatCycleManagementStatCycleCreatedServiceServer) OnMessage(context.Context, *StatCycleCreated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatCycleManagementStatCycleCreatedServiceServer) mustEmbedUnimplementedStatCycleManagementStatCycleCreatedServiceServer() {
}

// UnsafeStatCycleManagementStatCycleCreatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatCycleManagementStatCycleCreatedServiceServer will
// result in compilation errors.
type UnsafeStatCycleManagementStatCycleCreatedServiceServer interface {
	mustEmbedUnimplementedStatCycleManagementStatCycleCreatedServiceServer()
}

func RegisterStatCycleManagementStatCycleCreatedServiceServer(s grpc.ServiceRegistrar, srv StatCycleManagementStatCycleCreatedServiceServer) {
	s.RegisterService(&StatCycleManagementStatCycleCreatedService_ServiceDesc, srv)
}

func _StatCycleManagementStatCycleCreatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatCycleCreated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatCycleManagementStatCycleCreatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatCycleManagementStatCycleCreatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatCycleManagementStatCycleCreatedServiceServer).OnMessage(ctx, req.(*StatCycleCreated))
	}
	return interceptor(ctx, in, info, handler)
}

// StatCycleManagementStatCycleCreatedService_ServiceDesc is the grpc.ServiceDesc for StatCycleManagementStatCycleCreatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatCycleManagementStatCycleCreatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatCycleManagementStatCycleCreatedService",
	HandlerType: (*StatCycleManagementStatCycleCreatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatCycleManagementStatCycleCreatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatCycleManagementStatCycleUpdatedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatCycleManagementStatCycleUpdatedService/OnMessage"
)

// StatCycleManagementStatCycleUpdatedServiceClient is the client API for StatCycleManagementStatCycleUpdatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatCycleManagementStatCycleUpdatedServiceClient interface {
	OnMessage(ctx context.Context, in *StatCycleUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statCycleManagementStatCycleUpdatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatCycleManagementStatCycleUpdatedServiceClient(cc grpc.ClientConnInterface) StatCycleManagementStatCycleUpdatedServiceClient {
	return &statCycleManagementStatCycleUpdatedServiceClient{cc}
}

func (c *statCycleManagementStatCycleUpdatedServiceClient) OnMessage(ctx context.Context, in *StatCycleUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatCycleManagementStatCycleUpdatedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatCycleManagementStatCycleUpdatedServiceServer is the server API for StatCycleManagementStatCycleUpdatedService service.
// All implementations must embed UnimplementedStatCycleManagementStatCycleUpdatedServiceServer
// for forward compatibility
type StatCycleManagementStatCycleUpdatedServiceServer interface {
	OnMessage(context.Context, *StatCycleUpdated) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatCycleManagementStatCycleUpdatedServiceServer()
}

// UnimplementedStatCycleManagementStatCycleUpdatedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatCycleManagementStatCycleUpdatedServiceServer struct {
}

func (UnimplementedStatCycleManagementStatCycleUpdatedServiceServer) OnMessage(context.Context, *StatCycleUpdated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatCycleManagementStatCycleUpdatedServiceServer) mustEmbedUnimplementedStatCycleManagementStatCycleUpdatedServiceServer() {
}

// UnsafeStatCycleManagementStatCycleUpdatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatCycleManagementStatCycleUpdatedServiceServer will
// result in compilation errors.
type UnsafeStatCycleManagementStatCycleUpdatedServiceServer interface {
	mustEmbedUnimplementedStatCycleManagementStatCycleUpdatedServiceServer()
}

func RegisterStatCycleManagementStatCycleUpdatedServiceServer(s grpc.ServiceRegistrar, srv StatCycleManagementStatCycleUpdatedServiceServer) {
	s.RegisterService(&StatCycleManagementStatCycleUpdatedService_ServiceDesc, srv)
}

func _StatCycleManagementStatCycleUpdatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatCycleUpdated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatCycleManagementStatCycleUpdatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatCycleManagementStatCycleUpdatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatCycleManagementStatCycleUpdatedServiceServer).OnMessage(ctx, req.(*StatCycleUpdated))
	}
	return interceptor(ctx, in, info, handler)
}

// StatCycleManagementStatCycleUpdatedService_ServiceDesc is the grpc.ServiceDesc for StatCycleManagementStatCycleUpdatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatCycleManagementStatCycleUpdatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatCycleManagementStatCycleUpdatedService",
	HandlerType: (*StatCycleManagementStatCycleUpdatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatCycleManagementStatCycleUpdatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatCycleManagementStatCycleResetService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatCycleManagementStatCycleResetService/OnMessage"
)

// StatCycleManagementStatCycleResetServiceClient is the client API for StatCycleManagementStatCycleResetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatCycleManagementStatCycleResetServiceClient interface {
	OnMessage(ctx context.Context, in *StatCycleReset, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statCycleManagementStatCycleResetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatCycleManagementStatCycleResetServiceClient(cc grpc.ClientConnInterface) StatCycleManagementStatCycleResetServiceClient {
	return &statCycleManagementStatCycleResetServiceClient{cc}
}

func (c *statCycleManagementStatCycleResetServiceClient) OnMessage(ctx context.Context, in *StatCycleReset, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatCycleManagementStatCycleResetService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatCycleManagementStatCycleResetServiceServer is the server API for StatCycleManagementStatCycleResetService service.
// All implementations must embed UnimplementedStatCycleManagementStatCycleResetServiceServer
// for forward compatibility
type StatCycleManagementStatCycleResetServiceServer interface {
	OnMessage(context.Context, *StatCycleReset) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatCycleManagementStatCycleResetServiceServer()
}

// UnimplementedStatCycleManagementStatCycleResetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatCycleManagementStatCycleResetServiceServer struct {
}

func (UnimplementedStatCycleManagementStatCycleResetServiceServer) OnMessage(context.Context, *StatCycleReset) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatCycleManagementStatCycleResetServiceServer) mustEmbedUnimplementedStatCycleManagementStatCycleResetServiceServer() {
}

// UnsafeStatCycleManagementStatCycleResetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatCycleManagementStatCycleResetServiceServer will
// result in compilation errors.
type UnsafeStatCycleManagementStatCycleResetServiceServer interface {
	mustEmbedUnimplementedStatCycleManagementStatCycleResetServiceServer()
}

func RegisterStatCycleManagementStatCycleResetServiceServer(s grpc.ServiceRegistrar, srv StatCycleManagementStatCycleResetServiceServer) {
	s.RegisterService(&StatCycleManagementStatCycleResetService_ServiceDesc, srv)
}

func _StatCycleManagementStatCycleResetService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatCycleReset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatCycleManagementStatCycleResetServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatCycleManagementStatCycleResetService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatCycleManagementStatCycleResetServiceServer).OnMessage(ctx, req.(*StatCycleReset))
	}
	return interceptor(ctx, in, info, handler)
}

// StatCycleManagementStatCycleResetService_ServiceDesc is the grpc.ServiceDesc for StatCycleManagementStatCycleResetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatCycleManagementStatCycleResetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatCycleManagementStatCycleResetService",
	HandlerType: (*StatCycleManagementStatCycleResetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatCycleManagementStatCycleResetService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatCycleManagementStatCycleDeletedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatCycleManagementStatCycleDeletedService/OnMessage"
)

// StatCycleManagementStatCycleDeletedServiceClient is the client API for StatCycleManagementStatCycleDeletedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatCycleManagementStatCycleDeletedServiceClient interface {
	OnMessage(ctx context.Context, in *StatCycleDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statCycleManagementStatCycleDeletedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatCycleManagementStatCycleDeletedServiceClient(cc grpc.ClientConnInterface) StatCycleManagementStatCycleDeletedServiceClient {
	return &statCycleManagementStatCycleDeletedServiceClient{cc}
}

func (c *statCycleManagementStatCycleDeletedServiceClient) OnMessage(ctx context.Context, in *StatCycleDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatCycleManagementStatCycleDeletedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatCycleManagementStatCycleDeletedServiceServer is the server API for StatCycleManagementStatCycleDeletedService service.
// All implementations must embed UnimplementedStatCycleManagementStatCycleDeletedServiceServer
// for forward compatibility
type StatCycleManagementStatCycleDeletedServiceServer interface {
	OnMessage(context.Context, *StatCycleDeleted) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatCycleManagementStatCycleDeletedServiceServer()
}

// UnimplementedStatCycleManagementStatCycleDeletedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatCycleManagementStatCycleDeletedServiceServer struct {
}

func (UnimplementedStatCycleManagementStatCycleDeletedServiceServer) OnMessage(context.Context, *StatCycleDeleted) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatCycleManagementStatCycleDeletedServiceServer) mustEmbedUnimplementedStatCycleManagementStatCycleDeletedServiceServer() {
}

// UnsafeStatCycleManagementStatCycleDeletedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatCycleManagementStatCycleDeletedServiceServer will
// result in compilation errors.
type UnsafeStatCycleManagementStatCycleDeletedServiceServer interface {
	mustEmbedUnimplementedStatCycleManagementStatCycleDeletedServiceServer()
}

func RegisterStatCycleManagementStatCycleDeletedServiceServer(s grpc.ServiceRegistrar, srv StatCycleManagementStatCycleDeletedServiceServer) {
	s.RegisterService(&StatCycleManagementStatCycleDeletedService_ServiceDesc, srv)
}

func _StatCycleManagementStatCycleDeletedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatCycleDeleted)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatCycleManagementStatCycleDeletedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatCycleManagementStatCycleDeletedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatCycleManagementStatCycleDeletedServiceServer).OnMessage(ctx, req.(*StatCycleDeleted))
	}
	return interceptor(ctx, in, info, handler)
}

// StatCycleManagementStatCycleDeletedService_ServiceDesc is the grpc.ServiceDesc for StatCycleManagementStatCycleDeletedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatCycleManagementStatCycleDeletedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatCycleManagementStatCycleDeletedService",
	HandlerType: (*StatCycleManagementStatCycleDeletedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatCycleManagementStatCycleDeletedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatisticCycleStatItemCycleCreatedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatisticCycleStatItemCycleCreatedService/OnMessage"
)

// StatisticCycleStatItemCycleCreatedServiceClient is the client API for StatisticCycleStatItemCycleCreatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticCycleStatItemCycleCreatedServiceClient interface {
	OnMessage(ctx context.Context, in *StatItemCycleCreated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statisticCycleStatItemCycleCreatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticCycleStatItemCycleCreatedServiceClient(cc grpc.ClientConnInterface) StatisticCycleStatItemCycleCreatedServiceClient {
	return &statisticCycleStatItemCycleCreatedServiceClient{cc}
}

func (c *statisticCycleStatItemCycleCreatedServiceClient) OnMessage(ctx context.Context, in *StatItemCycleCreated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatisticCycleStatItemCycleCreatedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticCycleStatItemCycleCreatedServiceServer is the server API for StatisticCycleStatItemCycleCreatedService service.
// All implementations must embed UnimplementedStatisticCycleStatItemCycleCreatedServiceServer
// for forward compatibility
type StatisticCycleStatItemCycleCreatedServiceServer interface {
	OnMessage(context.Context, *StatItemCycleCreated) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatisticCycleStatItemCycleCreatedServiceServer()
}

// UnimplementedStatisticCycleStatItemCycleCreatedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticCycleStatItemCycleCreatedServiceServer struct {
}

func (UnimplementedStatisticCycleStatItemCycleCreatedServiceServer) OnMessage(context.Context, *StatItemCycleCreated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatisticCycleStatItemCycleCreatedServiceServer) mustEmbedUnimplementedStatisticCycleStatItemCycleCreatedServiceServer() {
}

// UnsafeStatisticCycleStatItemCycleCreatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticCycleStatItemCycleCreatedServiceServer will
// result in compilation errors.
type UnsafeStatisticCycleStatItemCycleCreatedServiceServer interface {
	mustEmbedUnimplementedStatisticCycleStatItemCycleCreatedServiceServer()
}

func RegisterStatisticCycleStatItemCycleCreatedServiceServer(s grpc.ServiceRegistrar, srv StatisticCycleStatItemCycleCreatedServiceServer) {
	s.RegisterService(&StatisticCycleStatItemCycleCreatedService_ServiceDesc, srv)
}

func _StatisticCycleStatItemCycleCreatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatItemCycleCreated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticCycleStatItemCycleCreatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticCycleStatItemCycleCreatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticCycleStatItemCycleCreatedServiceServer).OnMessage(ctx, req.(*StatItemCycleCreated))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticCycleStatItemCycleCreatedService_ServiceDesc is the grpc.ServiceDesc for StatisticCycleStatItemCycleCreatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticCycleStatItemCycleCreatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatisticCycleStatItemCycleCreatedService",
	HandlerType: (*StatisticCycleStatItemCycleCreatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatisticCycleStatItemCycleCreatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}

const (
	StatisticCycleStatItemCycleUpdatedService_OnMessage_FullMethodName = "/accelbyte.social.statistic.v1.StatisticCycleStatItemCycleUpdatedService/OnMessage"
)

// StatisticCycleStatItemCycleUpdatedServiceClient is the client API for StatisticCycleStatItemCycleUpdatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticCycleStatItemCycleUpdatedServiceClient interface {
	OnMessage(ctx context.Context, in *StatItemCycleUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type statisticCycleStatItemCycleUpdatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticCycleStatItemCycleUpdatedServiceClient(cc grpc.ClientConnInterface) StatisticCycleStatItemCycleUpdatedServiceClient {
	return &statisticCycleStatItemCycleUpdatedServiceClient{cc}
}

func (c *statisticCycleStatItemCycleUpdatedServiceClient) OnMessage(ctx context.Context, in *StatItemCycleUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StatisticCycleStatItemCycleUpdatedService_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticCycleStatItemCycleUpdatedServiceServer is the server API for StatisticCycleStatItemCycleUpdatedService service.
// All implementations must embed UnimplementedStatisticCycleStatItemCycleUpdatedServiceServer
// for forward compatibility
type StatisticCycleStatItemCycleUpdatedServiceServer interface {
	OnMessage(context.Context, *StatItemCycleUpdated) (*emptypb.Empty, error)
	mustEmbedUnimplementedStatisticCycleStatItemCycleUpdatedServiceServer()
}

// UnimplementedStatisticCycleStatItemCycleUpdatedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticCycleStatItemCycleUpdatedServiceServer struct {
}

func (UnimplementedStatisticCycleStatItemCycleUpdatedServiceServer) OnMessage(context.Context, *StatItemCycleUpdated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedStatisticCycleStatItemCycleUpdatedServiceServer) mustEmbedUnimplementedStatisticCycleStatItemCycleUpdatedServiceServer() {
}

// UnsafeStatisticCycleStatItemCycleUpdatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticCycleStatItemCycleUpdatedServiceServer will
// result in compilation errors.
type UnsafeStatisticCycleStatItemCycleUpdatedServiceServer interface {
	mustEmbedUnimplementedStatisticCycleStatItemCycleUpdatedServiceServer()
}

func RegisterStatisticCycleStatItemCycleUpdatedServiceServer(s grpc.ServiceRegistrar, srv StatisticCycleStatItemCycleUpdatedServiceServer) {
	s.RegisterService(&StatisticCycleStatItemCycleUpdatedService_ServiceDesc, srv)
}

func _StatisticCycleStatItemCycleUpdatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatItemCycleUpdated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticCycleStatItemCycleUpdatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticCycleStatItemCycleUpdatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticCycleStatItemCycleUpdatedServiceServer).OnMessage(ctx, req.(*StatItemCycleUpdated))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticCycleStatItemCycleUpdatedService_ServiceDesc is the grpc.ServiceDesc for StatisticCycleStatItemCycleUpdatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticCycleStatItemCycleUpdatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.social.statistic.v1.StatisticCycleStatItemCycleUpdatedService",
	HandlerType: (*StatisticCycleStatItemCycleUpdatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _StatisticCycleStatItemCycleUpdatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/social/statistic/v1/statistic.proto",
}
